name: film_freund
description: An application to discover new films and organize what to watch next.
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  gap:
  email_validator:
  flutter_riverpod: ^1.0.0-dev.11
  equatable:
  http:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  hive:
  path_provider:
  uuid:
  stream_transform:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  arb_generator:
  intl_utils: #^2.3.0
    git:
      url: https://github.com/defuncart/fork_intl_utils
      ref: feature/ignore-avoid_catches_without_on_clauses-always_use_package_imports-generated-code
  build_runner:
  mockito:
  json_serializable:
  flutter_test_ui:
  network_image_mock:

flutter:
  uses-material-design: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "intl_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets_dev/l10n
  output_dir: lib/generated